### PR TITLE
Lua support update

### PR DESCRIPTION
**Pull request by mpeterv**
* Install into $HOME/.lua instead of ./here
* Run pip with sudo
* Implement cache_slug
* Some small fixes

Now, what else do we need:

* More people!
* Supporting PRs to other travis repos - travis-core, travis-web, possibly travis-yaml?

### CODE REVIEW

**Comment by mpeterv** [comment]
I'm not sure if I like busted being installed and run by default. It and its dependencies are not very stable, that is, sometimes it's necessary to installed a pinned version of busted or a dependency beforehand.

**Comment by camoy** [comment]
This looks excellent. It seems to me that busted is the most commonly used/well maintained unit test framework for Lua. Which would be preferred, lunit?

**Comment by mpeterv** [comment]
busted is definitely the most popular testing framework, but there are quite a lot of projects that don't use it. If `luarocks install busted` fails (like it used to fail this week because lua-term, its dependency, couldn't compile on Lua 5.3), the build fails for these projects. And projects that do use busted don't have a chance to install a working version of a dependency before installing busted.

Maybe we could get another opinion on this? Did Hisham answer you?

**Comment by camoy** [comment]
That seems reasonable to me. I haven't heard from Hisham yet.

**Pull request merged**
